server:
  port: 8443
  servlet:
    context-path: /
    session:
      cookie:
        same-site: lax
        secure: true
      timeout: 15m # Het han session sau 15 phut khong hoat đong
  ssl:
    enabled: true
    key-store: classpath:shoeshop.p12
    key-store-password: ShoeshopTLS@2025
    key-password: ShoeshopTLS@2025
    key-store-type: PKCS12
    key-alias: shoeshop
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shoeshop"
    username: shoeshop
    password: shoeshop123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    prefix: classpath:/templates/webapp/
    # Đặt đường dẫn cho thư mục templates của bạn
    suffix: .html                         # Phần mở rộng của các tệp mẫu
    mode: HTML                            # Định dạng HTML
    encoding: UTF-8                       # Mã hóa ký tự
    cache: false                          # Vô hiệu hóa bộ nhớ đệm khi phát triển
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenpro449@gmail.com
    password: tcud wueu xklx jnlr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB